extend type Query {
  ratings: [Rating!]!
}

type User {
  id: Int!
  name: String
}

type Rating {
  id: Int!
  rating: Int
  user: User
  book: Book
}

extend type Book @key(fields: "id") {
  id: Int! @external
  ratings: [Rating!]!
}
